# Generated by Django 6.0.3 on 2026-03-22 05:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_customuser_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='UserSettings',
        ),
    ]
