# Generated by Django 6.0.3 on 2026-03-30 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='note',
            field=models.TextField(default=None),
        ),
    ]
