# Generated by Django 6.0.3 on 2026-03-30 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_expense_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
