# Generated by Django 6.0.3 on 2026-03-30 14:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_expense_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='period',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], default='monthly', max_length=20),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['category'], name='api_expense_categor_abfaf9_idx'),
        ),
    ]
