# Generated by Django 6.0.3 on 2026-03-30 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_budget_period_expense_api_expense_categor_abfaf9_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('confirmed', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='receiptitem',
            name='api_receipt_categor_688cc0_idx',
        ),
        migrations.RemoveIndex(
            model_name='receipt',
            name='api_receipt_user_id_fe7572_idx',
        ),
        migrations.AddField(
            model_name='expense',
            name='receipt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.receipt'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user', 'date'], name='api_expense_user_id_43c900_idx'),
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.category'),
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.expense'),
        ),
        migrations.RemoveField(
            model_name='receiptitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='receiptitem',
            name='receipt',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='date',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='merchant',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='total',
        ),
        migrations.AddIndex(
            model_name='expenseitem',
            index=models.Index(fields=['category'], name='api_expense_categor_33b098_idx'),
        ),
        migrations.DeleteModel(
            name='ReceiptItem',
        ),
    ]
