# Generated by Django 6.0.3 on 2026-04-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_category_color_category_icon_alter_expense_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(choices=[('shopping-cart', 'Shopping Cart'), ('utensils', 'Utensils'), ('car', 'Car'), ('home', 'Home'), ('heart', 'Heart'), ('gamepad-2', 'Gamepad'), ('shirt', 'Shirt'), ('dumbbell', 'Dumbbell'), ('plane', 'Plane'), ('coffee', 'Coffee'), ('book-open', 'Book'), ('music', 'Music'), ('gift', 'Gift'), ('dog', 'Dog'), ('scissors', 'Scissors'), ('briefcase', 'Briefcase'), ('graduation-cap', 'Graduation Cap'), ('pill', 'Pill'), ('wrench', 'Wrench'), ('wifi', 'Wifi'), ('baby', 'Baby'), ('fuel', 'Fuel'), ('circle-parking', 'Parking'), ('bus', 'Bus'), ('bike', 'Bike'), ('tv', 'TV'), ('smartphone', 'Smartphone'), ('receipt', 'Receipt'), ('landmark', 'Landmark'), ('tag', 'Tag')], default='tag', max_length=50),
        ),
    ]
