# Generated by Django 6.0.3 on 2026-04-21 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_category_icon'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='expenseitem',
            name='api_expense_categor_33b098_idx',
        ),
        migrations.DeleteModel(
            name='ExpenseItem',
        ),
    ]
