"""
Django settings for tallyAPI project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

from decouple import AutoConfig

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
env = AutoConfig(search_path=BASE_DIR.parent)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default='django-insecure-8(==5yr4xi#xw-zp(ib(2fe6ufj9$)wy4mz#^k(&@6+3=m61tc')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',

    'allauth',
    'allauth.account',
    'allauth.headless',
    # 'allauth.socialaccount', 

    'ninja_extra',
    'api',

    'storages',
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  # must be first
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

# ── Allauth ───────────────────────────────────────────────
HEADLESS_ONLY = True

HEADLESS_ADAPTER = "api.adapters.CustomHeadlessAdapter"

ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*", "password2*"]

ACCOUNT_EMAIL_VERIFICATION = "none"  # "mandatory" in production

HEADLESS_FRONTEND_URLS = {
    "account_confirm_email": "http://localhost:5173/verify-email/{key}",
    "account_reset_password": "http://localhost:5173/reset-password",
    "account_reset_password_from_key": "http://localhost:5173/reset-password/{key}",
}

CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',
]
CORS_ALLOW_CREDENTIALS = True  # Required to send cookies cross-origin


# CSRF
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:5173',
]

CSRF_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SECURE = False
CSRF_COOKIE_HTTPONLY = False

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

ROOT_URLCONF = 'tallyAPI.urls'

WSGI_APPLICATION = 'tallyAPI.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# Prefer explicit PostgreSQL env vars. If they are not present, fall back to
# SQLite so local setup still works without a database server.
postgres_name = env('DATABASE_NAME', default='')

if postgres_name:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': postgres_name,
            'USER': env('DATABASE_USER', default='postgres'),
            'PASSWORD': env('DATABASE_PASSWORD', default=''),
            'HOST': env('DATABASE_HOST', default='localhost'),
            'PORT': env('DATABASE_PORT', default='5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/New_York'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (receipt images)
AWS_ACCESS_KEY_ID = env('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = env('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = env('AWS_STORAGE_BUCKET_NAME')
AWS_S3_REGION_NAME = env('AWS_S3_REGION_NAME', default='us-east-1')
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = None

STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

MEDIA_URL = f'https://{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com/'


# Session cookie security
SESSION_COOKIE_HTTPONLY = True 
SESSION_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_SECURE = not DEBUG  # True in production (requires HTTPS)

PRODUCTION_HOST = env('PRODUCTION_HOST', default='tally.bwalls.dev')

if env('DJANGO_ENV', default='development') == 'production':
    ALLOWED_HOSTS = [PRODUCTION_HOST]
    # Same-domain architecture: frontend and backend share one DO domain,
    # so CORS is not needed. CSRF_TRUSTED_ORIGINS covers the session cookie.
    CORS_ALLOWED_ORIGINS = []
    CSRF_TRUSTED_ORIGINS = [f'https://{PRODUCTION_HOST}']
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True
    HEADLESS_FRONTEND_URLS = {
        "account_confirm_email": f"https://{PRODUCTION_HOST}/verify-email/{{key}}",
        "account_reset_password": f"https://{PRODUCTION_HOST}/reset-password",
        "account_reset_password_from_key": f"https://{PRODUCTION_HOST}/reset-password/{{key}}",
    }
    # Trust the DO load balancer's forwarded headers
    USE_X_FORWARDED_HOST = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
else:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1']
    CORS_ALLOWED_ORIGINS = ['http://localhost:5173']
    CSRF_TRUSTED_ORIGINS = ['http://localhost:5173']
    HEADLESS_FRONTEND_URLS = {
        "account_confirm_email": "http://localhost:5173/verify-email/{key}",
        "account_reset_password": "http://localhost:5173/reset-password",
        "account_reset_password_from_key": "http://localhost:5173/reset-password/{key}",
    }