# Generated by Django 6.0.3 on 2026-03-18 06:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='budget',
            name='unique_budeget_category_motnh',
        ),
        migrations.AddField(
            model_name='budget',
            name='spent',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='budget',
            name='limit',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='receiptitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(fields=('user', 'category', 'month'), name='unique_budget_category_month '),
        ),
        migrations.RemoveField(
            model_name='budget',
            name='current',
        ),
    ]
