# Generated by Django 6.0.3 on 2026-03-19 17:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_budget_unique_budeget_category_motnh_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['user'], name='api_receipt_user_id_2c7e7e_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['user', 'date'], name='api_receipt_user_id_fe7572_idx'),
        ),
        migrations.AddIndex(
            model_name='receiptitem',
            index=models.Index(fields=['category'], name='api_receipt_categor_688cc0_idx'),
        ),
    ]
