import {
  ShoppingCart, UtensilsCrossed, Car, Home, Heart,
  Gamepad2, Shirt, Dumbbell, Plane, Coffee,
  BookOpen, Music, Gift, Dog, Scissors,
  Briefcase, GraduationCap, Pill, Wrench, Wifi,
  Baby, Fuel, CircleParking, Bus, Bike,
  Tv, Smartphone, Receipt, Landmark, Tag,
} from "lucide-react";

export const iconMap = {
  "shopping-cart":   ShoppingCart,
  "utensils":        UtensilsCrossed,
  "car":             Car,
  "home":            Home,
  "heart":           Heart,
  "gamepad-2":       Gamepad2,
  "shirt":           Shirt,
  "dumbbell":        Dumbbell,
  "plane":           Plane,
  "coffee":          Coffee,
  "book-open":       BookOpen,
  "music":           Music,
  "gift":            Gift,
  "dog":             Dog,
  "scissors":        Scissors,
  "briefcase":       Briefcase,
  "graduation-cap":  GraduationCap,
  "pill":            Pill,
  "wrench":          Wrench,
  "wifi":            Wifi,
  "baby":            Baby,
  "fuel":            Fuel,
  "circle-parking":  CircleParking,
  "bus":             Bus,
  "bike":            Bike,
  "tv":              Tv,
  "smartphone":      Smartphone,
  "receipt":         Receipt,
  "landmark":        Landmark,
  "tag":             Tag,
};